#!/bin/bash
passaggi_saltati = 0
printf "Benvenuto, script by David Isztl & Michel Basili\n"
printf "Questo script installerà:\n\tSSHD modificato\n\tSTUNNEL\n\tssllogmux\n\tBRO 2.0\nCon le relative dipendenze\n"
printf "Script testato su Centos 6.x\n"
read -p "Sei sicuro di voler procedere? <y/N> " prompt
if [[ $prompt == "y" || $prompt == "Y" || $prompt == "yes" || $prompt == "Yes" ]]
then
clear
######## PASSO 1: INSTALLAZIONE DIPENDENZE
yum groupinstall "Development tools" -y
yum install wget zlib-devel openssl-devel ncurses-devel file-libs file-devel python-devel libpcap-devel -y
cd /home
wget --no-check-certificate http://download.fedoraproject.org/pub/epel/6/x86_64/epel-release-6-8.noarch.rpm
rpm -ivh epel-release-6-8.noarch.rpm
yum install libnet cpan cmake nc -y
unset prompt
######## FINE PASSO 1
######## PASSO 2: Installazione openssh 5.8 modificato
read -p "Vuoi installare openssh 5.8 modificato? <y/N> " prompt
if [[ $prompt == "y" || $prompt1 == "Y" || $prompt == "yes" || $prompt == "Yes" ]]
then
cd /home
wget --no-check-certificate  https://auditing-sshd.googlecode.com/files/openssh-5.8p1-hpn13v11-3.10.tar.gz
tar -zxvf openssh-5.8p1-hpn13v11-3.10.tar.gz
rm openssh-5.8p1-hpn13v11-3.10.tar.gz
cd openssh-5.8p1-hpn13v11-3.10/openssh-5.8p1-hpn13v11
yum remove openssh* -y
./configure --with-nerscmod
make
make install
wget --no-check-certificate https://raw.githubusercontent.com/trakons/sshd_stunnel/master/sshd_start
mv sshd_start /etc/init.d/sshd
chmod +x /etc/init.d/sshd
chkconfig --add /etc/init.d/sshd
cp /usr/local/etc/sshd_config /etc/ssh/sshd_config
service sshd restart
else
let "passaggi_saltati += 1"
printf "Installazione openssh 5.8 modificato annullato\n"
fi
unset prompt
######## FINE PASSO 2
######## PASSO 3: Installazione stunnel
read -p "Vuoi installare stunnel? <y/N> " prompt
if [[ $prompt == "y" || $prompt == "Y" || $prompt == "yes" || $prompt == "Yes" ]]
then
yum install stunnel -y
openssl genrsa -out privatekey.pem 1024
openssl req -new -x509 -key privatekey.pem -out cacert.pem -days 1095
cat privatekey.pem cacert.pem >> /etc/stunnel/stunnel.pem
chmod 600 /etc/stunnel/stunnel.pem
mkdir /var/run/stunnel
chown nobody.nobody /var/run/stunnel
sudo cp /usr/share/doc/stunnel*/stunnel.conf-sample
cp /usr/share/doc/stunnel-*/stunnel.conf-sample /etc/stunnel/stunnel.conf
wget --no-check-certificate https://raw.githubusercontent.com/trakons/sshd_stunnel/master/script1
mv script1 /etc/stunnel/stunnel.conf
wget --no-check-certificate https://raw.githubusercontent.com/trakons/sshd_stunnel/master/script2
mv script2 /etc/init.d/stunnel
chmod +x /etc/init.d/stunnel
chkconfig --add stunnel
service stunnel start
else
let "passaggi_saltati += 1"
printf "Installazione stunnel annullato\n"
fi
unset prompt
######## FINE PASSO 3
######## PASSO 4: Installazione cpan
read -p "Vuoi installare cpan? <y/N> " prompt
if [[ $prompt == "y" || $prompt == "Y" || $prompt == "yes" || $prompt == "Yes" ]]
then
wget --no-check-certificate -O - http://cpanmin.us | perl - --self-upgrade
wget --no-check-certificate https://raw.githubusercontent.com/trakons/sshd_stunnel/master/cpan_install_auto
chmod +x cpan_install_auto
./cpan_install_auto
else
let "passaggi_saltati += 1"
printf "Installazione cpan annullato\n"
fi
unset prompt
######## FINE PASSO 4
######## PASSO 5: Installazione ssllogmux
read -p "Vuoi installare ssllogmux? <y/N> " prompt
if [[ $prompt == "y" || $prompt == "Y" || $prompt == "yes" || $prompt == "Yes" ]]
then
mkdir /home/ssllogmux
wget --no-check-certificate https://raw.githubusercontent.com/trakons/sshd_stunnel/master/script3
mv script3 /home/ssllogmux/ssllogmux
openssl genrsa -out privatekey.pem 1024
openssl req -new -x509 -key privatekey.pem -out cacert.pem -days 1095
cat privatekey.pem cacert.pem >> /home/ssllogmux/server-key.pem
cat privatekey.pem cacert.pem >> /home/ssllogmux/SSL.pm
chmod 600 /home/ssllogmux/server-key.pem
chmod 600 /home/ssllogmux/SSL.pm
cd /home/ssllogmux
wget --no-check-certificate https://raw.githubusercontent.com/trakons/sshd_stunnel/master/script4
mv script4 start
chmod +x start
else
let "passaggi_saltati += 1"
printf "Installazione ssllogmux annullato\n"
fi
unset prompt
######## FINE PASSO 5
######## PASSO 6: Installazione di bro
read -p "Vuoi installare bro? <y/N> " prompt
if [[ $prompt == "y" || $prompt == "Y" || $prompt == "yes" || $prompt == "Yes" ]]
then
mkdir /home/bro_inst
cd /home/bro_inst
wget --no-check-certificate http://www.bro.org/downloads/archive/Bro-2.0-Linux-x86_64.rpm
yum localinstall Bro-*.rpm -y
cp /home/openssh-5.8p1-hpn13v11-3.10/bro_policy/sshd_auth.bro /opt/bro/share/bro/site
cp /home/openssh-5.8p1-hpn13v11-3.10/bro_policy_2.0/sshd_const.bro /opt/bro/share/bro/site
cp /home/openssh-5.8p1-hpn13v11-3.10/bro_policy_2.0/sshd_core.bro /opt/bro/share/bro/site
cp /home/openssh-5.8p1-hpn13v11-3.10/bro_policy_2.0/sshd_policy.bro /opt/bro/share/bro/site
cp /home/openssh-5.8p1-hpn13v11-3.10/bro_policy_2.0/sshd_sftp.bro /opt/bro/share/bro/site
cp /home/openssh-5.8p1-hpn13v11-3.10/bro_policy_2.0/sshd_input_stream.bro /opt/bro/share/bro/site
touch /opt/bro/share/bro/site/isshd.bro
echo @load sshd_core >> /opt/bro/share/bro/site/isshd.bro
echo @load sshd_const >> /opt/bro/share/bro/site/isshd.bro
echo @load sshd_auth >> /opt/bro/share/bro/site/isshd.bro
echo @load sshd_policy >> /opt/bro/share/bro/site/isshd.bro
echo @load sshd_sftp >> /opt/bro/share/bro/site/isshd.bro
echo @load sshd_input_stream.bro >> /opt/bro/share/bro/site/isshd.bro
wget --no-check-certificate https://raw.githubusercontent.com/trakons/sshd_stunnel/master/conf_bro
rm /opt/bro/etc/broctl.cfg
cp conf_bro /opt/bro/etc/broctl.cfg
rm /opt/bro/share/bro/site/sshd_core.bro
wget --no-check-certificate https://raw.githubusercontent.com/trakons/sshd_stunnel/master/ssh_core
cp ssh_core /opt/bro/share/bro/site/sshd_core.bro
/opt/bro/bin/broctl install
/opt/bro/bin/broctl check
/opt/bro/bin/broctl start
/opt/bro/bin/broctl status
else
let "passaggi_saltati += 1"
printf "Installazione bro annullato\n"
fi
unset prompt
######## FINE PASSO 6
######## PASSO 7: Se tutto ok, allora parte l'ascolto dei log sulla porta 799
clear
if (())$passaggi_saltati >= 1))
then
	printf "\t\tATTENZIONE, hai saltato %i passaggi\n" $passaggi_saltati
fi
printf "\n\n\tScript By David Isztl & Michel Basili\n\n"
printf "Complimenti, molto probabilmente l'installazione è andata a buon fine.\n"
printf "Come testare se funziona:\n\tDopo il ravvio della macchina andare nella cartela di ssllogmux (default:"/home/ssllogmux") e lanciare ./start\n\tSuggessivamente vedrete tutte le sessioni ssh monitorati.\n"
printf "Se funziona allora nel file /home/ssllogmux/ssllogmux.log ci sarà tutto ciò che passa per le sessioni ssh.\n\n\n"
read -p "Vuoi riavviare automatcamente? <y/N> " prompt
if [[ $prompt == "y" || $prompt == "Y" || $prompt == "yes" || $prompt == "Yes" ]]
then
reboot
else
printf "Riavvio manuale\n"
fi
######## FINE PASSO 7
else
printf "Installazione annullata\n"
  exit 0
fi
