#!/usr/bin/perl
BEGIN{
  unless( eval { require Proc::PID::File } ){
    require CPAN;
    CPAN::Shell->force("install","Proc::PID::File");
  }
}
BEGIN{
  unless( eval { require Proc::ProcessTable } ){
    require CPAN;
    CPAN::Shell->force("install","Proc::ProcessTable");
  }
}
BEGIN{
  unless( eval { require Proc::Daemon } ){
    require CPAN;
    CPAN::Shell->force("install","Proc::Daemon");
  }
}
BEGIN{
  unless( eval { require IO::Socket::SSL } ){
    require CPAN;
    CPAN::Shell->force("install","IO::Socket::SSL");
  }
}
