#! /bin/sh

# source function library
. /etc/rc.d/init.d/functions

LOCK_FILE=/var/run/ssllogmux.pid

start() {
	if [ -f $LOCK_FILE ];
		then
			echo "ssllogmux is already running!"
			exit 0
		else
			stty tostop
			echo "Starting ssllogmux:"
			cd /home/ssllogmux
			perl ssllogmux -d -f -k /home/ssllogmux/server-key.pem -c /home/ssllogmux/SSL.pm &
			echo "OK"
	fi
}

stop() {
	if [ -f $LOCK_FILE ];
                then
			echo "Stopping ssllogmux:"
			cat /var/run/ssllogmux.pid | xargs kill
			for i in {1..70}
			do
				echo -n "."
				sleep 1
			done
			echo "OK" 
			stty -tostop
                else
                        echo "ssllogmux is already Stopping!"
			exit 0
        fi
}

status() {
	if [ -f $LOCK_FILE ];
                 then
                        echo "ssllogmux is running!"
		 else
                        echo "ssllogmux is stopping!"
	fi
}

restart() {
	if [ -f $LOCK_FILE ];
                 then
                        echo "Stopping ssllogmux:"
			cat /var/run/ssllogmux.pid | xargs kill
			for i in {1..70}
                        do
                                echo -n  "."
                                sleep 1
                        done
			echo "OK"
			echo "Starting ssllogmux :"
                        cd /home/ssllogmux
			perl ssllogmux -d -f -k /home/ssllogmux/server-key.pem -c /home/ssllogmux/SSL.pm &
			echo "OK"
                else
                        stty tostop
			echo  "Starting ssllogmux :"
                        cd /home/ssllogmux
			perl ssllogmux -d -f -k /home/ssllogmux/server-key.pem -c /home/ssllogmux/SSL.pm &
        		echo "OK"
	fi
}

case "$1" in
    start)
        start
        ;;
    stop)
        stop
        ;;
    status)
	status
        ;;
    restart)
     	restart
        ;;
    *)
        echo "Usage:  {start|stop|status|restart}"
        exit 1
        ;;
esac
exit 1
